version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
build_script:
- ps: '& ".\build.ps1"'
test: off
artifacts:
- path: '\whats-new*.nupkg'
  name: Chocolatey
deploy: 
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: nB1mf4p3RJjf/Qsqjx0s/D7WWM7nnKUu/wN2x3+XUxe+mNyg0U8pS9jHw49oiJkA
  on:
    branch: master